### PR TITLE
progressbar and other minor improvement

### PR DESCRIPTION
**Pull request by rmarabini**
hi @vabrishami ,

  This pull request includes a few minor improvements to localrec that you may want to add to the master branch:

1) added another 4 icosahedral symmetries (this is important if the 3D map was created by eman). The code is already in Scipion so we only need to add more options in the form to the "symGrp" parameter

2) the parameter "relaxSym" is never used in the code so I have commented it out. A couple of users have asked my about it and the answer "It does nothing at all" is not a good one. The parameter may be uncommented as soon as it is used.

3) I am using about a million subparticles and that means that the program is running for more than one hour without showing any output. It would be a good idea to implement a scrollbar that gives a visual clue on the number of coordinates/particles processed. This is what the new file "progressbar.py" does. 

    hope you like the suggestions

   Roberto

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@rmarabini Similar comment than in relion plugin...instead of spreading the progressbar.py implementation over many plugins...try to get it into the main core repo. Maybe pyworkflow.utils is a good sub-module for it. 
More over, the is some boilerplate code that is repeated (see below), so you might want to define a function for it:
```python
                print(progress(), end='')
                sys.stdout.flush()
                progress.current += step
```

**Comment by rmarabini** [comment]
@delarosatrevin,

   I agree that progressbar should go into scipion main code. But before starting that fight I wanted to know if you were OK with the progressbar idea. I guess from your comment that you are happy with it so I will create a pull request for progressbar in scipion.

**Comment by delarosatrevin** [comment]
Yes, I like the progressbar idea...then on each plugin developers can decide if it is worth using it or not. And of course better to have the progressbar code centralized.

**Comment by vabrishami** [comment]
So will you make a new PR?

**Comment by rmarabini** [comment]
Hi,

  I think we should process the current pull request (with the small
modification described below -it is already included in the pull request).
The reason is the following: even  if modelbar is included in scipion main
code  it will take a while until scipion next release arrives (based in the
last release it will take 1 year) so my suggestion would be to include in
scipion-em-localrec the follwoing include

try:
    from pyworkflow.em.uitils.progressbar import Progressbar
except:
    from localrec.progressbar import ProgressBar

In this way scipion-em-localrec may start using progressbar today and be
compatible with the present release of scipion
and it will use the scipion core progressbar whenever is available. That
is, we keep compatibility with present
 and future releases of scipion. It makes no sense to wait for the next
release of scipion since it will take a while and we are not sure if the
user that updates scipion-em-locarec will also update scipion at the same
time. Plugins have advantages and disadvantages.

   Roberto

**Comment by delarosatrevin** [comment]
@rmarabini Don't be so pesimistic...last Scipion release contained xmipp and all other packages code...now it is only the core. 

Another detail...the pyworkflow.utils is a submodule...so you should not import from specific implementations files...it should be:

```python
from pyworkflow.utils import ProgressBar
```

I don't see the urgency to have progress bar right now...so you argument could also be to try to import it from the core...and if not present, not use it (as it is now).

Anyway, the final decision is up to the plugins developers.

**Pull request merged**
