### PR TITLE
Use scipion3 in the readme

### PR DESCRIPTION
**Pull request by pconesa**

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@pconesa Why changing to scipion3 here? I commonly use scipion also for my 3.x version

**Comment by pconesa** [comment]
Well, scipion3 is the default name for the launcher that the installer creates. We all have scipion3 launcher. I think is more generic.

**Comment by delarosatrevin** [comment]
I install it in a different way and keep scipion...I think it is more general to have scipion pointing to the latest version and maybe alias more specific as scipion3 (a la python). If not you will need to. change all docs and commands every major version

**Comment by pconesa** [comment]
You might be right. We can think about this in the next major release. Now, all of our users have scipion3, not that sure if they have an alias.

**Comment by delarosatrevin** [comment]
I mean that we could have both, not to force to change everything to
scipion3 now.

**Pull request merged**
