### PR TITLE
modify symmetry definition and add filter by distance to center

### PR DESCRIPTION
**Pull request by rmarabini**

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Hi @rmarabini,

I'm helping @JuhaHuiskonen to review and merge this PR. It seems that it has been waiting for a while here. Would you like to update it to Python3/Scipion3?

**Comment by vabrishami** [comment]
I have already added this change to the code. So I think we can close it if RM confirms.

**Comment by rmarabini** [comment]
I think it is already in devel and updated to python3.  So very likely
you may close the PR.


   Roberto

**Comment by delarosatrevin** [comment]
Thanks @vabrishami and @rmarabini!
I will close this PR then.

**Pull request closed without merging**
